/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aalap.learn.gradle;

import java.io.File;

import org.gradle.tooling.BuildLauncher;
import org.gradle.tooling.GradleConnector;
import org.gradle.tooling.ProjectConnection;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	ProjectConnection projectConnection = GradleConnector.newConnector().forProjectDirectory(new File("C:\\Users\\adesai\\AALAP-Learning-example\\gradle\\learn-gradle")).connect();
    	try {
            BuildLauncher build = projectConnection.newBuild();
            build.forTasks("build");
            build.run();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
        	projectConnection.close();
        }
    	System.out.println("C:\\Users\\adesai\\AALAP-Learning-example\\gradle\\learn-gradle");
        System.out.println(new App().getGreeting());
    }
}
