/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jaxrs.wsrs.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Hello classUnderTest = new Hello();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.);
    }
}
